dropout: 0.1
ffn_activation: swiglu
hidden_dim: 768
init_scheme: xavier_uniform
max_rel_pos: null
max_seq_len: 265
n_heads_ra: 3
n_heads_sa: 9
n_layers: 12
norm_type: rmsnorm
pad_token_id: 3
pe_type: rope
positional_symbols_sinusoidal: false
ra_rel_activation: sigmoid
ra_type: rca
relative_symbols_rope: true
relsymbolic_neighborhood_size: 2
sequence_boundary_policy: eos_document
symbol_retrieval: relative
symbolic_attn_n_heads: null
symbolic_use_bias: false
tie_lm_head: true
use_bias_out: true
vocab_size: 16384
