dropout: 0.1
ffn_activation: swiglu
hidden_dim: 768
init_scheme: normal_0_02_scaled_projection
max_rel_pos: null
max_seq_len: 514
n_heads_ra: 3
n_heads_sa: 9
n_layers: 12
norm_type: layernorm
pad_token_id: 3
pe_type: rope
positional_symbols_sinusoidal: false
ra_rel_activation: identity
ra_type: rca
relsymbolic_neighborhood_size: 2
sequence_boundary_policy: eos_document
symbol_retrieval: relative
symbolic_attn_n_heads: 4
symbolic_use_bias: true
tie_lm_head: false
use_bias_out: false
vocab_size: 16384
